### PR TITLE
feat: add support for Font Awesome Pro

### LINKED ISSUE #3: Add support for Font Awesome pro icons
## Description

This was suggested by [@flowdee on Twitter](https://twitter.com/flowdee/status/1275436985696399360), it would be nice to be able to support Font Awesome icons for Pro users.

I currently don't use Font Awesome pro so I wouldn't be able to test this. Also, the [Font Awesome licence](https://fontawesome.com/support#license-dos) states that the icons shouldn't be included in open source (although they are [looking into how this could be possible](https://fontawesome.com/support#use-opensource)).

## Possible implementation

I'm not really sure how this would work as it needs to include the icons in the package somehow. 🤔

### PR DESCRIPTION
**Pull request by owenvoke**
This adds support for using Font Awesome Pro icons.

1. Install Font Awesome Pro as usual through npm (`npm i --save @fortawesome/fontawesome-pro`)
1. Run the "sync" command (`php artisan blade-fontawesome:sync-pro`)
1. Profit 😉

Check out #3 for more information.

---

**Things to do:**

- ~~Update `bin/compile.sh` to work with pro icons, or probably add it as a PHP script instead that can be run for any directory of SVGs (that way it can be integrated into the sync command).~~

---

- [x] I have read the **[CONTRIBUTING](https://github.com/owenvoke/blade-fontawesome/blob/main/.github/CONTRIBUTING.md)** document.

Closes #3

### CODE REVIEW

**Comment by Gummibeer** [comment]
**LGTM** 🚀
It works like expected! 🤩

**Comment by owenvoke** [comment]
Well, this is now working with the compilation. However, it could definitely be better, any thoughts on cleaning it up? 👍🏻

**Comment by adddz** [comment]
May I know when this will be released in a new version so I can use it in my project?
Last version (1.3) does not have the `blade-fontawesome:sync-pro` command.

Thanks!

**Comment by owenvoke** [comment]
@adddz, sure. :+1: Been busy with other things recently. I'll release a v1.4.0 later today with this.

**Pull request merged**
